
/*--------------------------------------------------------------------*/
/* Sparrow OAM Instance - DO NOT EDIT - automatically generated file. */
/* Generated by instance-gen.py on 2016-06-30 17:39:03.               */
/*--------------------------------------------------------------------*/

/*
 * Copyright (c) 2016, SICS, Swedish ICT.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *   3. Neither the name of the copyright holders nor the
 *      names of its contributors may be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

/*--------------------------------------------------------------------*/
/* Sparrow OAM Instance - DO NOT EDIT - automatically generated file. */
/*--------------------------------------------------------------------*/


#ifndef INSTANCE_RADIO_VAR_H_
#define INSTANCE_RADIO_VAR_H_

#include "sparrow-oam.h"

#define INSTANCE_RADIO_OBJECT_TYPE      0x0090DA0303010014ULL
#define INSTANCE_RADIO_LABEL            "802.15.4 radio"

/* Enum types for instance radio */

typedef enum {
  RADIO_RESET_CAUSE_NONE                 = 0,
  RADIO_RESET_CAUSE_LOCKUP               = 1,
  RADIO_RESET_CAUSE_DEEP_SLEEP           = 2,
  RADIO_RESET_CAUSE_SOFTWARE             = 3,
  RADIO_RESET_CAUSE_WATCHDOG             = 4,
  RADIO_RESET_CAUSE_HARDWARE             = 5,
  RADIO_RESET_CAUSE_POWER_FAIL           = 6,
  RADIO_RESET_CAUSE_COLD_START           = 7,
} radio_reset_cause_t;

typedef enum {
  RADIO_EXT_RESET_CAUSE_NONE             = 0,
  RADIO_EXT_RESET_CAUSE_NORMAL           = 1,
  RADIO_EXT_RESET_CAUSE_WATCHDOG         = 2,
} radio_ext_reset_cause_t;

/* Variables for instance radio */
#define VARIABLE_RADIO_CHANNEL           0x100
#define VARIABLE_RADIO_PAN_ID            0x101
#define VARIABLE_RADIO_BEACON_RESPONSE   0x102
#define VARIABLE_RADIO_MODE              0x103
#define VARIABLE_RADIO_SCAN_MODE         0x104
#define VARIABLE_RADIO_SERIAL_MODE       0x105
#define VARIABLE_RADIO_STAT_LENGTH       0x106
#define VARIABLE_RADIO_STAT_DATA         0x107
#define VARIABLE_RADIO_CONTROL_API_VERSION 0x108
#define VARIABLE_RADIO_SUPPLY_STATUS     0x109
#define VARIABLE_RADIO_BATTERY_SUPPLY_TIME 0x10a
#define VARIABLE_RADIO_SUPPLY_VOLTAGE    0x10b
#define VARIABLE_RADIO_FRONTPANEL_INFO   0x10c
#define VARIABLE_RADIO_WATCHDOG          0x10d
#define VARIABLE_RADIO_RESET_CAUSE       0x10e
#define VARIABLE_RADIO_ERROR_CODE        0x10f
#define VARIABLE_RADIO_UNIT_BOOT_TIMER   0x200
#define VARIABLE_RADIO_STAT_DEBUG_LENGTH 0x201
#define VARIABLE_RADIO_STAT_DEBUG_DATA   0x202

static const sparrow_oam_variable_t instance_radio_variables[] = {
{ 0x100,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x101,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x102,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_ARRAY,    SPARROW_OAM_VECTOR_DEPTH_DONT_CHECK },
{ 0x103,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x104,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x105,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x106,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x107,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_ARRAY,    SPARROW_OAM_VECTOR_DEPTH_DONT_CHECK },
{ 0x108,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x109,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x10a,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x10b,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x10c,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x10d,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x10e,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x10f,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x200,  8, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x201,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x202,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_ARRAY,    SPARROW_OAM_VECTOR_DEPTH_DONT_CHECK },
};

#endif /* INSTANCE_RADIO_VAR_H_ */
