/*
 * Copyright (c) 2012-2016, Yanzi Networks AB.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *    1. Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *    3. Neither the name of the copyright holders nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#ifndef INSTANCE0_VAR_H_
#define INSTANCE0_VAR_H_

static const sparrow_oam_variable_t instance0_variables[] = {
  { 0x0c0,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_UNIT_CONTROLLER_WATCHDOG */
  { 0x0c1,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_UNIT_CONTROLLER_STATUS */
  { 0x0c2, 32, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_UNIT_CONTROLLER_ADDRESS */
  { 0x0c3,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_COMMUNICATION_STYLE */
  { 0x0c8,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CONFIGURATION_STATUS */
  { 0x0c9,  8, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_UNIT_BOOT_TIMER */
  { 0x0ca,  4, SPARROW_OAM_WRITABILITY_WO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_HARDWARE_RESET */
  { 0x0cb,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_READ_THIS_COUNTER */
  { 0x0cc, 16, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_SW_REVISION */
  { 0x0cd,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_TLV_GROUPING */
  { 0x0ce,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_LOCATION_ID */
  { 0x0cf,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_OWNER_ID */
  { 0x0d0,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_SLEEP_DEFAULT_AWAKE_TIME */
  { 0x0e0,  8, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_CAPABILITIES */
  { 0x0e1,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_BOOTLOADER_VERSION */
  { 0x0e2,  4, SPARROW_OAM_WRITABILITY_WO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_FACTORY_DEFAULT */
  { 0x0e3,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_TIME_SINCE_LAST_GOOD_UC_RX */
  { 0x0e4,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_IDENTIFY_CHASSIS */
  { 0x0e5,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_RESET_CAUSE */
  { 0x0e6,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_RECEIVED_OAM_PDUS */
  { 0x0e7,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_TRANSMITTED_OAM_PDUS */
  { 0x0e8,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_TRANSMITTED_EVENT_OAM_PDUS */
  { 0x0e9,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_INFO_HIGHLIGHTS */
  { 0x0ea,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_ENUM   ,  0 }, /* VARIABLE_CHASSIS_ACTIVITY_LEVEL */
  { 0x0eb,  4, SPARROW_OAM_WRITABILITY_WO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_RESTART_NETSELECT */
  { 0x0ec,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_ACTIVITY_CYCLES */
  { 0x0ed,  4, SPARROW_OAM_WRITABILITY_WO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_ACTIVITY_COMMAND */
  { 0x0ee,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_CHASSIS_WAKEUPP_INFO */
  { 0x10d,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 }, /* VARIABLE_PSP_PORTAL_STATUS */
};

#endif /* INSTANCE0_VAR_H_ */
