
/*--------------------------------------------------------------------*/
/* Sparrow OAM Instance - DO NOT EDIT - automatically generated file. */
/* Generated by instance-gen.py on 2016-06-29 00:17:51.               */
/*--------------------------------------------------------------------*/

/*
 * Copyright (c) 2016, SICS, Swedish ICT.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *   3. Neither the name of the copyright holders nor the
 *      names of its contributors may be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

/*--------------------------------------------------------------------*/
/* Sparrow OAM Instance - DO NOT EDIT - automatically generated file. */
/*--------------------------------------------------------------------*/


#ifndef INSTANCE_LEDS_VAR_H_
#define INSTANCE_LEDS_VAR_H_

#include "sparrow-oam.h"

#define INSTANCE_LEDS_OBJECT_TYPE      0x0090DA030201001EULL
#define INSTANCE_LEDS_LABEL            "LEDs"

/* Enum types for instance leds */

typedef enum {
  LEDS_COLORS_RED                        = 1,
  LEDS_COLORS_GREEN                      = 2,
  LEDS_COLORS_BLUE                       = 3,
  LEDS_COLORS_YELLOW                     = 4,
} leds_colors_t;

/* Variables for instance leds */
#define VARIABLE_NUMBER_OF_LEDS          0x100
#define VARIABLE_LED_CONTROL             0x101
#define VARIABLE_LED_SET                 0x102
#define VARIABLE_LED_CLEAR               0x103
#define VARIABLE_LED_TOGGLE              0x104
#define VARIABLE_LED_STATE               0x105
#define VARIABLE_LED_STATE_COUNT         0x106

static const sparrow_oam_variable_t instance_leds_variables[] = {
{ 0x100,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x101,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x102,  4, SPARROW_OAM_WRITABILITY_WO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x103,  4, SPARROW_OAM_WRITABILITY_WO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x104,  4, SPARROW_OAM_WRITABILITY_WO, SPARROW_OAM_FORMAT_INTEGER,  0 },
{ 0x105,  4, SPARROW_OAM_WRITABILITY_RW, SPARROW_OAM_FORMAT_ARRAY,    SPARROW_OAM_VECTOR_DEPTH_DONT_CHECK },
{ 0x106,  4, SPARROW_OAM_WRITABILITY_RO, SPARROW_OAM_FORMAT_ARRAY,    SPARROW_OAM_VECTOR_DEPTH_DONT_CHECK },
};

#endif /* INSTANCE_LEDS_VAR_H_ */
